### PR TITLE
Uploaded the babylon

### PR DESCRIPTION
**Pull request by drdhaval2785**
Dear @vvasuki Check whether the babylon passes or not.
If any changes are required in the babylon, let me know.

### CODE REVIEW

**Comment by drdhaval2785** [comment]
I am not sure whether the `**` tags will be rendered well in stardict or not.
Do you want me to convert them to `<b></b>` tags?

**Comment by drdhaval2785** [comment]
As this was trivial- I have pushed `<b></b>` tags instead of markdown language.

**Comment by drdhaval2785** [comment]
I checked locally. The babylon now generates proper stardict files.
4365 headwords.

**Comment by vvasuki** [comment]
Thanks! Could you please send a pull requests with the scripts to https://github.com/indic-dict/dict-curation/tree/master/dict_curation_projects instead (under a new upasargaartha_chandrikaa module)?

Also, can you send a PR with the babylon to https://github.com/indic-dict/stardict-sanskrit/tree/master/sa-head/sa-entries under the directory upasargArthachandrikA ?

**Comment by drdhaval2785** [comment]
I will do so. But one thing. 
I had also made some minor changes in the .md files as well. How can we merge only that part? I don't know how to do this in github.

**Comment by vvasuki** [comment]
> I will do so. But one thing. I had also made some minor changes in the .md files as well. How can we merge only that part? I don't know how to do this in github.

Simple - you delete everything but the md files from your branch drdhaval2785:content . Then I'll be able to merge just the md changes.

**Comment by drdhaval2785** [comment]
OK

**Comment by drdhaval2785** [comment]
Removed python, babylon and a json from the PR.
You can now merge.

**Pull request merged**
